<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.kernotec.driverschedule</groupId>
    <artifactId>driver-schedule</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>driver-schedule-bom</artifactId>
  <packaging>pom</packaging>

  <properties>
    <org.springdoc.version>2.2.0</org.springdoc.version>
    <poi.version>5.4.1</poi.version>
    <open-csv.version>5.3</open-csv.version>
    <commons-csv.version>1.8</commons-csv.version>
    <jasperreports.version>6.21.5</jasperreports.version>
    <firebase.version>9.8.0</firebase.version>
    <logstash-logback.version>8.0</logstash-logback.version>
  </properties>


  <dependencyManagement>
    <dependencies>
      <!-- INTERNAL DEPENDENCIES -->
      <dependency>
        <groupId>com.kernotec.driverschedule</groupId>
        <artifactId>driver-schedule-common</artifactId>
        <version>${project.version}</version>
      </dependency>

      <dependency>
        <groupId>com.kernotec.driverschedule</groupId>
        <artifactId>driver-schedule-notification</artifactId>
        <version>${project.version}</version>
      </dependency>

      <dependency>
        <groupId>com.kernotec.driverschedule</groupId>
        <artifactId>driver-schedule-person</artifactId>
        <version>${project.version}</version>
      </dependency>

      <dependency>
        <groupId>com.kernotec.driverschedule</groupId>
        <artifactId>driver-schedule-socket</artifactId>
        <version>${project.version}</version>
      </dependency>

      <dependency>
        <groupId>com.kernotec.driverschedule</groupId>
        <artifactId>driver-schedule-user-api</artifactId>
        <version>${project.version}</version>
      </dependency>

      <dependency>
        <groupId>com.kernotec.driverschedule</groupId>
        <artifactId>driver-schedule-report</artifactId>
        <version>${project.version}</version>
      </dependency>

      <dependency>
        <groupId>com.kernotec.driverschedule</groupId>
        <artifactId>driver-schedule-resource</artifactId>
        <version>${project.version}</version>
      </dependency>

      <!-- EXTERNAL DEPENDENCIES -->
      <dependency>
        <groupId>net.logstash.logback</groupId>
        <artifactId>logstash-logback-encoder</artifactId>
        <version>${logstash-logback.version}</version>
      </dependency>

      <dependency>
        <groupId>org.springdoc</groupId>
        <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        <version>${org.springdoc.version}</version>
      </dependency>
      <dependency>
        <groupId>org.springdoc</groupId>
        <artifactId>springdoc-openapi-starter-webmvc-api</artifactId>
        <version>${org.springdoc.version}</version>
      </dependency>

      <dependency>
        <groupId>org.apache.poi</groupId>
        <artifactId>poi</artifactId>
        <version>${poi.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.poi</groupId>
        <artifactId>poi-ooxml</artifactId>
        <version>${poi.version}</version>
      </dependency>

      <dependency>
        <groupId>com.opencsv</groupId>
        <artifactId>opencsv</artifactId>
        <version>${open-csv.version}</version>
      </dependency>

      <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-csv</artifactId>
        <version>${commons-csv.version}</version>
      </dependency>

      <dependency>
        <groupId>net.sf.jasperreports</groupId>
        <artifactId>jasperreports</artifactId>
        <version>${jasperreports.version}</version>
      </dependency>

      <dependency>
        <groupId>com.google.firebase</groupId>
        <artifactId>firebase-admin</artifactId>
        <version>${firebase.version}</version>
      </dependency>

    </dependencies>
  </dependencyManagement>

</project>
