<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.kernotec</groupId>
    <artifactId>core-boot-3</artifactId>
    <version>develop</version>
  </parent>

  <groupId>com.kernotec.driverschedule</groupId>
  <artifactId>driver-schedule</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>

  <modules>
    <module>driver-schedule-bom</module>
    <module>driver-schedule-auth</module>
    <module>driver-schedule-service</module>
    <module>driver-schedule-notification</module>
    <module>driver-schedule-common</module>
    <module>driver-schedule-person</module>
    <module>driver-schedule-user-api</module>
    <module>driver-schedule-socket</module>
    <module>driver-schedule-report</module>
    <module>driver-schedule-resource</module>
  </modules>

    <build>
      <pluginManagement>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.13.0</version>
          </plugin>
        </plugins>
      </pluginManagement>
    </build>

  <distributionManagement>
    <snapshotRepository>
      <id>nexus</id>
      <name>maven-snapshots</name>
      <url>https://registry.kernotec.com/repository/maven-snapshots</url>
    </snapshotRepository>
    <repository>
      <id>nexus</id>
      <url>https://registry.kernotec.com/repository/maven-releases</url>
    </repository>
  </distributionManagement>

  <properties>
    <java.version>17</java.version>
    <maven.compiler.source>${java.version}</maven.compiler.source>
    <maven.compiler.target>${java.version}</maven.compiler.target>

    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
  </properties>

</project>
