<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.kernotec.driverschedule</groupId>
    <artifactId>driver-schedule-bom</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <relativePath>../driver-schedule-bom</relativePath>
  </parent>

  <artifactId>driver-schedule-service</artifactId>

  <build>
    <finalName>${project.name}</finalName>

    <plugins>
      <plugin>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <groupId>org.springframework.boot</groupId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <executions>
          <execution>
            <id>default-compile</id>
            <phase>none</phase>
          </execution>
          <execution>
            <id>default-testCompile</id>
            <phase>none</phase>
          </execution>
          <execution>
            <id>compile</id>
            <phase>compile</phase>
            <goals>
              <goal>compile</goal>
            </goals>
          </execution>
          <execution>
            <id>testCompile</id>
            <phase>test-compile</phase>
            <goals>
              <goal>testCompile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <!-- INTERNAL -->
    <dependency>
      <groupId>com.kernotec.driverschedule</groupId>
      <artifactId>driver-schedule-common</artifactId>
    </dependency>

    <dependency>
      <groupId>com.kernotec.driverschedule</groupId>
      <artifactId>driver-schedule-person</artifactId>
    </dependency>

    <dependency>
      <groupId>com.kernotec.driverschedule</groupId>
      <artifactId>driver-schedule-notification</artifactId>
    </dependency>

    <dependency>
      <groupId>com.kernotec.driverschedule</groupId>
      <artifactId>driver-schedule-socket</artifactId>
    </dependency>

    <dependency>
      <groupId>com.kernotec.driverschedule</groupId>
      <artifactId>driver-schedule-report</artifactId>
    </dependency>

    <!-- CORE -->
    <dependency>
      <groupId>com.kernotec</groupId>
      <artifactId>core-jpa</artifactId>
    </dependency>
    <dependency>
      <groupId>com.kernotec</groupId>
      <artifactId>core-postgresql</artifactId>
    </dependency>
    <dependency>
      <groupId>com.kernotec</groupId>
      <artifactId>core-command</artifactId>
    </dependency>
    <dependency>
      <groupId>com.kernotec</groupId>
      <artifactId>core-rest</artifactId>
    </dependency>
    <dependency>
      <groupId>com.kernotec</groupId>
      <artifactId>core-security</artifactId>
    </dependency>
    <dependency>
      <groupId>com.kernotec</groupId>
      <artifactId>core-test</artifactId>
    </dependency>
    <dependency>
      <groupId>com.kernotec</groupId>
      <artifactId>core-api</artifactId>
    </dependency>

    <!-- EXTERNAL -->
    <dependency>
      <groupId>net.logstash.logback</groupId>
      <artifactId>logstash-logback-encoder</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-starter-webmvc-api</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-hateoas</artifactId>
    </dependency>

    <dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi-ooxml</artifactId>
    </dependency>

    <dependency>
      <groupId>com.opencsv</groupId>
      <artifactId>opencsv</artifactId>
    </dependency>

    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-csv</artifactId>
    </dependency>

    <dependency>
      <groupId>net.sf.jasperreports</groupId>
      <artifactId>jasperreports</artifactId>
    </dependency>
  </dependencies>

  <profiles>
    <profile>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <id>dev</id>
      <properties>
        <spring.profiles.active>dev</spring.profiles.active>
      </properties>
    </profile>

    <profile>
      <id>prod</id>
      <properties>
        <spring.profiles.active>prod</spring.profiles.active>
      </properties>
    </profile>
  </profiles>

</project>
