#SERVER
server:
  port: ${SERVER_PORT_AUTH:7800}

# DRIVER SCHEDULE AUTH
kernotec:
  info:
    title: ${APP_TITLE_AUTH:DRIVER SCHEDULE AUTH API}
    description: ${APP_DESCRIPTION_AUTH:Driver Schedule authentication API}
    version: ${APP_VERSION_AUTH:local}
  servers:
    - url: ${APP_SERVER_URL_AUTH:http://localhost:7800}
      description: ${APP_SERVER_DESCRIPTION_AUTH:API of Driver Schedule Auth}
  allowed-origins: ${APP_CORS_ALLOWED_ORIGINS_AUTH:http://localhost:4200}

# SPRING
spring:
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: driver-schedule-auth

  # SERVLET
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  # LIQUIBASE
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: ${DB_SCHEMA_AUTH:public}

  # JPA
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA_AUTH:public}
        type:
          json_format_mapper: com.kernotec.core.config.HibernateFormatMapper
        format_sql: false
        dialect: com.kernotec.core.config.PGDialect
        jdbc:
          time_zone: UTC
        connection:
          characterEncoding: UTF-8
          charSet: UTF-8
          useUnicode: true

  # DATASOURCE
  datasource:
    url: jdbc:postgresql://${DB_HOST_AUTH:localhost}:${DB_PORT_AUTH:5541}/${DB_NAME_AUTH:driver_schedule_auth_db}
    username: ${DB_USERNAME_AUTH:dbusr}
    password: ${DB_PASSWORD_AUTH:dbpass}
    hikari:
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 60000
      minimum-idle: 5
      maximum-pool-size: 50

# SWAGGER
springdoc:
  api-docs:
    path: /${spring.application.name}/v3/api-docs
  swagger-ui:
    path: /${spring.application.name}/swagger-ui.html
    enabled: true
    doc-expansion: none
    operations-sorter: alpha
    tags-sorter: alpha

# LOGGING
logging:
  level:
    root: ${LOGGING_LEVEL:INFO}

# OAUTH2 CONFIG
oauth2-config:
  secret-key: ${OAUTH2_JWT_SECRET:secret-key}
  audience: ${OAUTH2_JWT_AUDIENCE:driver-schedule-audience}
  access-token-exp: ${OAUTH2_JWT_ACCESS_TOKEN_EXP:3600}
  access-token-exp-type: ${OAUTH2_JWT_ACCESS_TOKEN_EXP_TYPE:seconds}
  refresh-token-exp: ${OAUTH2_JWT_REFRESH_TOKEN_EXP:86400}
  refresh-token-exp-type: ${OAUTH2_JWT_REFRESH_TOKEN_EXP_TYPE:seconds}
  refresh-token-secure: ${OATH2_JWT_REFRESH_TOKEN_SECURE:dev}
  admin-password: ${OAUTH2_ADMIN_PASSWORD:admin-pass}


rate-limit-bucket-config:
  capacity: ${RATE_LIMIT_BUCKET_CAPACITY:50}
  refill-tokens: ${RATE_LIMIT_BUCKET_REFILL_TOKENS:10}
  refill-period-in-seconds: ${RATE_LIMIT_BUCKET_REFILL_PERIOD:1}
  bucket-cache-expire-in-minutes: ${RATE_LIMIT_BUCKET_CACHE_EXPIRE:60}
  bucket-cache-max-size: ${RATE_LIMIT_BUCKET_CACHE_MAX_SIZE:10000}
