# SERVER
server:
  port: ${SERVER_PORT_APP:7801}

# DRIVER SCHEDULE
kernotec:
  info:
    title: ${APP_TITLE:DRIVER SCHEDULE API}
    description: ${APP_DESCRIPTION:Driver Schedule operational API}
    version: ${APP_VERSION:local}
  servers:
    - url: ${APP_SERVER_URL:http://localhost:7801}
      description: ${APP_SERVER_DESCRIPTION:API of Driver Schedule application}

# SPRING
spring:
  # PROFILES
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: driver-schedule-service

  # SERVERLET
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  # LIQUIBASE
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: ${DB_SCHEMA:public}

    #JPA
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:public}
        type:
          json_format_mapper: com.kernotec.core.config.HibernateFormatMapper
        format_sql: false
        dialect: com.kernotec.core.config.PGDialect
        jdbc:
          time_zone: UTC
        connection:
          characterEncoding: UTF-8
          charSet: UTF-8
          useUnicode: true

  # DATASOURCE
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:driver_schedule_db}
    username: ${DB_USERNAME:dbusr}
    password: ${DB_PASSWORD:dbpass}
    hikari:
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 60000
      minimum-idle: 5
      maximum-pool-size: 50

# SWAGGER
springdoc:
  api-docs:
    path: /${spring.application.name}/v3/api-docs
  swagger-ui:
    path: /${spring.application.name}/swagger-ui.html
    enabled: true
    doc-expansion: none
    operations-sorter: alpha
    tags-sorter: alpha

# LOGGING
logging:
  level:
    root: ${LOGGING_LEVEL:WARN}
    #org.hibernate:
    #sql: DEBUG
    #orm.results: TRACE
    #resource.jdbc.bind: TRACE
    #type.descriptor.sql.BasicBinder: TRACE

# OAUTH2 CONFIG
oauth2-config:
  host: ${OAUTH2_HOST:http://localhost:7801}
  realm: ${OAUTH2_REALM:driver-schedule-auth}
  resource: ${OAUTH2_RESOURCE:driver-schedule}
  secret-key: ${OAUTH2_JWT_SECRET:secret-key}

# WEB SOCKET CONFIG
web-socket-config:
  broker-prefix: /topic
  app-prefix: /app
  private-message-prefix: /queue
  user-destination-prefix: /user
  endpoint: /ws-driver-schedule

# MODULES CONFIG API
modules-app:
  app-auth:
    scheme: ${MS_AUTH_SCHEME:http}
    host: ${MS_AUTH_HOST:localhost}
    port: ${SERVER_PORT_AUTH:7800}